### ISSUE TITLE
Autocomplete does not show

### ISSUE THREAD

**Issue by tpetricek** [ionide/ionide-atom-fsharp#218]
I do not get autocomplete when typing `.` in the following case:

```
let ``a b`` = [| System.Random() |]
``a b``.[0]. // <- no autocomplete here
```

It seems this needs both back-tick name and indexing.

**Comment by Krzysztof-Cieslak** [comment]
It might be actually problem with FSAC, will need to investigate.

**Comment by kontomondo** [comment]
For me it takes about 10 seconds to get the autocomplete list (on FSharp.Data sourcecode), and it's instant on VSCode
