### ISSUE TITLE
Broken auto completion for integer literals.

### ISSUE THREAD

**Issue by ReverseBlade** [ionide/ionide-atom-fsharp#234]
If I write  (1).  for it should show 4 members of System.Int32 but instead it shows all possible types.

![vscode](https://cloud.githubusercontent.com/assets/4114592/15505722/5816900c-21cd-11e6-9cb2-db8c1d2ac0df.png)

**Comment by Krzysztof-Cieslak** [comment]
Problem with background language services, moved to FSAC repo.
