### ISSUE TITLE
Very slow under Ubuntu

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-atom-fsharp#238]
Hello guys,

I am using Ionide FSharp under Ubuntu 16.04. And the intelliseence and linter process is very slow.
It take around 15-20 sec to update.

I have a really small project has I just started it yesterday.

Any idea ?

**Comment by Krzysztof-Cieslak** [comment]
it sounds like a problem with FSAC. CC: @rneatherway

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce on any of my machines
