### ISSUE TITLE
PascalCase identifiers

### ISSUE THREAD

**Issue by haf** [ionide/ionide-atom-fsharp#251]
Hi there,

I would prefer camelCase identifiers. Who decided it should be PascalCase? Nowadays ionide complains and I'm enforcing camelCase throughout my projects.

Regards,
Henrik

**Comment by Krzysztof-Cieslak** [comment]
In Atom? I've thought you're trying out Code ;)

Anyway, I guess you're talking about hints from FSharpLint - for VSCode you can create settings file as described in their documentation - http://fsprojects.github.io/FSharpLint/. For Atom we don't support it yet but I'm planning to add it soon [On vacation right now, so it will take a moment]

Also if it's really annoying you can turn off FSharpLint hints completely either in Atom or Code using plugin settings.

**Comment by haf** [comment]
Darn, wrong repo, sorry. Yes, in Code.

My beef is with the default bring imo wrong...
