### ISSUE TITLE
FSI now runs from the project root dir rather than the dir containing the file

### ISSUE THREAD

**Issue by JonCanning** [ionide/ionide-atom-fsharp#252]
On a Mac since the 2.5 update, running `#load` from a file in a subdir fails since the target file cannot be found

**Comment by Krzysztof-Cieslak** [comment]
1. This is repo for Atom plugin not VS Code
2. This was reported in https://github.com/ionide/ionide-vscode-fsharp/issues/162
3. Fixed in `2.5.1`

**Comment by JonCanning** [comment]
That's embarrassing. Thanks!
