### ISSUE TITLE
Keyword exception is not highlighted for F# files

### ISSUE THREAD

**Issue by egamma** [ionide/ionide-atom-fsharp#255]
_From @hanpari on December 23, 2016 20:8_

- VSCode Version:
1.8.1
- OS Version:
Win10
Steps to Reproduce:

1. open *.fs or *.fsx
2. write 
    exception MyError of string

[see here](https://docs.microsoft.com/cs-cz/dotnet/articles/fsharp/language-reference/exception-handling/exception-types)

Type exception should be highlighted as in reference page

_Copied from original issue: Microsoft/vscode#17784_

**Comment by egamma** [comment]
VS Code is using the grammar provided by this repository.

CC @aeschli

**Comment by cloudRoutine** [comment]
we haven't update this repo in quite some time, but the itself grammar has been updated. we use https://github.com/ionide/ionide-fsgrammar to provide the grammar for both vscode and atom

**Comment by egamma** [comment]
@cloudRoutine thanks for letting us know!
