### ISSUE TITLE
Incorrect highlighting for open when namespace starts with lower case char

### ISSUE THREAD

**Issue by rojepp** [ionide/ionide-atom-fsharp#256]
<img width="193" alt="screenshot 2017-01-15 18 34 36" src="https://cloud.githubusercontent.com/assets/445888/21964921/463a1b64-db55-11e6-9d4f-e0bb081d65fa.png">

**Comment by Krzysztof-Cieslak** [comment]
Should be reported in https://github.com/ionide/ionide-fsgrammar
