### ISSUE TITLE
'Queue' is not defined

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-atom-fsharp#262]
![image](https://cloud.githubusercontent.com/assets/1834919/23388612/29832c06-fd31-11e6-8708-bd7b88da3e6c.png)

"The value, constructor, namespace or type `Queue` is not defined."

**Comment by lilred** [comment]
Wrong repo >_< This was meant for ionide/ionide-vscode-fsharp

**Comment by alexboii** [comment]
Can confirm the reproduction of this error on Fedora 25, ionide 2.35.5, vsc version 1.9.1 

![here](https://i.imgur.com/7FjnOfJ.png)
