### ISSUE TITLE
Projects files with <link> files don't work properly

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-atom-fsharp#49]
```
    <Compile Include="..\sr.fs">
      <Link>ErrorText\sr.fs</Link>
    </Compile>
```

Project such as FCS use file links and it would be great if they could opened and edited in Atom:
This is an ideal project to aim to support:
https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj

**Comment by Krzysztof-Cieslak** [comment]
Hmm. That's interesting case. But one of the main point of Atom is that it's using file system instead of project files. So I'm not sure if it's even possible. 

Maybe workaround would be parsing `fsproj` files and creating temporary symbolic links in file system for ever file link from project file.

**Comment by 7sharp9** [comment]
Is it not possible to create virtual entries in Atom to represent the links?

Its a pity if this doesn't work, my main use case for using Atom or Sublime is generally editing compiler source, it would be nice to have tooltips and completion and also without red underlined errors everywhere like this:

![screen shot 2015-05-20 at 11 24 32](https://cloud.githubusercontent.com/assets/588746/7723752/da878a96-fee2-11e4-857d-8b84e66346ed.png)

**Comment by Krzysztof-Cieslak** [comment]
Hmm, well looks like the problem is with not finding `fsproj` file for currently opened file. Can You open `fsproj` file to force parsing it, come back to file You are trying to edit and check if there still is an issue?

**Comment by 7sharp9** [comment]
If I open the project file and reopen the file the errors disappear, although tooltips don't work for all the types on the page.  If I then open the file where one of the missing tooltips is defined like `Symbols.fs` and go back to `Expr.fs` then the errors reappear.

**Comment by 7sharp9** [comment]
When you force parse the project file are you starting Background parsing for the project?

**Comment by Krzysztof-Cieslak** [comment]
When users open new file (and it's F# file) I try to find `fsproj` file in same folder as file. If I find project file I'm calling `fsautocomplete.exe` and executing https://github.com/fsharp/fsharpbinding/blob/master/FSharp.AutoComplete/Program.fs#L392.

Same story for `fsproj` file, if user open file I just execute same thing.

**Comment by 7sharp9** [comment]
Hmm, from what I can see it just parses the project file, it doesn't start a background compilation of the project, if it did then a request for any file in the project to be parsed would return results based on the background check.
